# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ViewLast.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(953, 986)
        MainWindow.setAcceptDrops(True)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(246,247,249);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.aBackgroundImage = QtWidgets.QLabel(self.centralwidget)
        self.aBackgroundImage.setGeometry(QtCore.QRect(20, 0, 911, 901))
        self.aBackgroundImage.setText("")
        self.aBackgroundImage.setPixmap(QtGui.QPixmap("imageonline-co-transparentimage.png"))
        self.aBackgroundImage.setScaledContents(True)
        self.aBackgroundImage.setObjectName("aBackgroundImage")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(580, 10, 161, 59))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.headPitchLabel = QtWidgets.QLabel(self.layoutWidget)
        self.headPitchLabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.headPitchLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.headPitchLabel.setObjectName("headPitchLabel")
        self.verticalLayout_3.addWidget(self.headPitchLabel)
        self.headPitchBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.headPitchBox.setDecimals(3)
        self.headPitchBox.setObjectName("headPitchBox")
        self.verticalLayout_3.addWidget(self.headPitchBox)
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(130, 610, 150, 50))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.kneePitchLabelRight = QtWidgets.QLabel(self.layoutWidget_3)
        self.kneePitchLabelRight.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.kneePitchLabelRight.setAlignment(QtCore.Qt.AlignCenter)
        self.kneePitchLabelRight.setObjectName("kneePitchLabelRight")
        self.verticalLayout_4.addWidget(self.kneePitchLabelRight)
        self.kneePitchRightBox = QtWidgets.QDoubleSpinBox(self.layoutWidget_3)
        self.kneePitchRightBox.setDecimals(3)
        self.kneePitchRightBox.setObjectName("kneePitchRightBox")
        self.verticalLayout_4.addWidget(self.kneePitchRightBox)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(590, 230, 291, 61))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.shoulderPitchLabelLeft = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.shoulderPitchLabelLeft.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.shoulderPitchLabelLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.shoulderPitchLabelLeft.setObjectName("shoulderPitchLabelLeft")
        self.verticalLayout_23.addWidget(self.shoulderPitchLabelLeft)
        self.shoulderPitchLeftBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_9)
        self.shoulderPitchLeftBox.setDecimals(3)
        self.shoulderPitchLeftBox.setObjectName("shoulderPitchLeftBox")
        self.verticalLayout_23.addWidget(self.shoulderPitchLeftBox)
        self.horizontalLayout_6.addLayout(self.verticalLayout_23)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.shoulderRollLabelLeft = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.shoulderRollLabelLeft.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.shoulderRollLabelLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.shoulderRollLabelLeft.setObjectName("shoulderRollLabelLeft")
        self.verticalLayout_24.addWidget(self.shoulderRollLabelLeft)
        self.shoulderRollLeftBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_9)
        self.shoulderRollLeftBox.setDecimals(3)
        self.shoulderRollLeftBox.setObjectName("shoulderRollLeftBox")
        self.verticalLayout_24.addWidget(self.shoulderRollLeftBox)
        self.horizontalLayout_6.addLayout(self.verticalLayout_24)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.elbowPitchLabeLeft = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.elbowPitchLabeLeft.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.elbowPitchLabeLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.elbowPitchLabeLeft.setObjectName("elbowPitchLabeLeft")
        self.verticalLayout_25.addWidget(self.elbowPitchLabeLeft)
        self.elbowPitchLeftBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_9)
        self.elbowPitchLeftBox.setDecimals(3)
        self.elbowPitchLeftBox.setObjectName("elbowPitchLeftBox")
        self.verticalLayout_25.addWidget(self.elbowPitchLeftBox)
        self.horizontalLayout_6.addLayout(self.verticalLayout_25)
        self.layoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_4.setGeometry(QtCore.QRect(630, 610, 149, 50))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.kneePitchLabelLeft = QtWidgets.QLabel(self.layoutWidget_4)
        self.kneePitchLabelLeft.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.kneePitchLabelLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.kneePitchLabelLeft.setObjectName("kneePitchLabelLeft")
        self.verticalLayout_5.addWidget(self.kneePitchLabelLeft)
        self.kneePitchLeftBox = QtWidgets.QDoubleSpinBox(self.layoutWidget_4)
        self.kneePitchLeftBox.setDecimals(3)
        self.kneePitchLeftBox.setObjectName("kneePitchLeftBox")
        self.verticalLayout_5.addWidget(self.kneePitchLeftBox)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(20, 240, 311, 61))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.elbowPitchLabelRight = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.elbowPitchLabelRight.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.elbowPitchLabelRight.setAlignment(QtCore.Qt.AlignCenter)
        self.elbowPitchLabelRight.setObjectName("elbowPitchLabelRight")
        self.verticalLayout_20.addWidget(self.elbowPitchLabelRight)
        self.elbowPitchRightBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_6)
        self.elbowPitchRightBox.setDecimals(3)
        self.elbowPitchRightBox.setObjectName("elbowPitchRightBox")
        self.verticalLayout_20.addWidget(self.elbowPitchRightBox)
        self.horizontalLayout_11.addLayout(self.verticalLayout_20)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.shoulderRollLabelRight = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.shoulderRollLabelRight.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.shoulderRollLabelRight.setAlignment(QtCore.Qt.AlignCenter)
        self.shoulderRollLabelRight.setObjectName("shoulderRollLabelRight")
        self.verticalLayout_21.addWidget(self.shoulderRollLabelRight)
        self.shoulderRollRightBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_6)
        self.shoulderRollRightBox.setDecimals(3)
        self.shoulderRollRightBox.setObjectName("shoulderRollRightBox")
        self.verticalLayout_21.addWidget(self.shoulderRollRightBox)
        self.horizontalLayout_11.addLayout(self.verticalLayout_21)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.shoulderPitchLabelRight = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.shoulderPitchLabelRight.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.shoulderPitchLabelRight.setAlignment(QtCore.Qt.AlignCenter)
        self.shoulderPitchLabelRight.setObjectName("shoulderPitchLabelRight")
        self.verticalLayout_22.addWidget(self.shoulderPitchLabelRight)
        self.shoulderPitchRightBox = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_6)
        self.shoulderPitchRightBox.setDecimals(3)
        self.shoulderPitchRightBox.setObjectName("shoulderPitchRightBox")
        self.verticalLayout_22.addWidget(self.shoulderPitchRightBox)
        self.horizontalLayout_11.addLayout(self.verticalLayout_22)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 900, 911, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_9.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout_9.setSpacing(100)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.clearButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout_9.addWidget(self.clearButton)
        self.setButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.setButton.setObjectName("setButton")
        self.horizontalLayout_9.addWidget(self.setButton)
        self.pos0Button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pos0Button.setObjectName("pos0Button")
        self.horizontalLayout_9.addWidget(self.pos0Button)
        self.layoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_5.setGeometry(QtCore.QRect(580, 80, 161, 59))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.headPitchLabel_2 = QtWidgets.QLabel(self.layoutWidget_5)
        self.headPitchLabel_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.headPitchLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.headPitchLabel_2.setObjectName("headPitchLabel_2")
        self.verticalLayout_2.addWidget(self.headPitchLabel_2)
        self.headYawBox = QtWidgets.QDoubleSpinBox(self.layoutWidget_5)
        self.headYawBox.setDecimals(3)
        self.headYawBox.setObjectName("headYawBox")
        self.verticalLayout_2.addWidget(self.headYawBox)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(630, 400, 185, 134))
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.hipYawLabelLeft = QtWidgets.QLabel(self.widget)
        self.hipYawLabelLeft.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.hipYawLabelLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.hipYawLabelLeft.setObjectName("hipYawLabelLeft")
        self.verticalLayout_16.addWidget(self.hipYawLabelLeft)
        self.hipYawLeftBox = QtWidgets.QDoubleSpinBox(self.widget)
        self.hipYawLeftBox.setDecimals(3)
        self.hipYawLeftBox.setObjectName("hipYawLeftBox")
        self.verticalLayout_16.addWidget(self.hipYawLeftBox)
        self.verticalLayout_6.addLayout(self.verticalLayout_16)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.hipRollLabelLeft = QtWidgets.QLabel(self.widget)
        self.hipRollLabelLeft.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.hipRollLabelLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.hipRollLabelLeft.setObjectName("hipRollLabelLeft")
        self.verticalLayout_17.addWidget(self.hipRollLabelLeft)
        self.hipRollLeftBox = QtWidgets.QDoubleSpinBox(self.widget)
        self.hipRollLeftBox.setDecimals(3)
        self.hipRollLeftBox.setObjectName("hipRollLeftBox")
        self.verticalLayout_17.addWidget(self.hipRollLeftBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_17)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.hipPitchLabelLeft = QtWidgets.QLabel(self.widget)
        self.hipPitchLabelLeft.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.hipPitchLabelLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.hipPitchLabelLeft.setObjectName("hipPitchLabelLeft")
        self.verticalLayout_13.addWidget(self.hipPitchLabelLeft)
        self.hipPitchLeftBox = QtWidgets.QDoubleSpinBox(self.widget)
        self.hipPitchLeftBox.setDecimals(3)
        self.hipPitchLeftBox.setObjectName("hipPitchLeftBox")
        self.verticalLayout_13.addWidget(self.hipPitchLeftBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_13)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(95, 400, 185, 134))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.hipYawLabelRight = QtWidgets.QLabel(self.widget1)
        self.hipYawLabelRight.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.hipYawLabelRight.setAlignment(QtCore.Qt.AlignCenter)
        self.hipYawLabelRight.setObjectName("hipYawLabelRight")
        self.verticalLayout_19.addWidget(self.hipYawLabelRight)
        self.hipYawRightBox = QtWidgets.QDoubleSpinBox(self.widget1)
        self.hipYawRightBox.setDecimals(3)
        self.hipYawRightBox.setObjectName("hipYawRightBox")
        self.verticalLayout_19.addWidget(self.hipYawRightBox)
        self.verticalLayout.addLayout(self.verticalLayout_19)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.hipPitchLabelRight = QtWidgets.QLabel(self.widget1)
        self.hipPitchLabelRight.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.hipPitchLabelRight.setAlignment(QtCore.Qt.AlignCenter)
        self.hipPitchLabelRight.setObjectName("hipPitchLabelRight")
        self.verticalLayout_12.addWidget(self.hipPitchLabelRight)
        self.hipPitchRightBox = QtWidgets.QDoubleSpinBox(self.widget1)
        self.hipPitchRightBox.setDecimals(3)
        self.hipPitchRightBox.setObjectName("hipPitchRightBox")
        self.verticalLayout_12.addWidget(self.hipPitchRightBox)
        self.horizontalLayout.addLayout(self.verticalLayout_12)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.hipRollLabelRight = QtWidgets.QLabel(self.widget1)
        self.hipRollLabelRight.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.hipRollLabelRight.setAlignment(QtCore.Qt.AlignCenter)
        self.hipRollLabelRight.setObjectName("hipRollLabelRight")
        self.verticalLayout_18.addWidget(self.hipRollLabelRight)
        self.hipRollRightBox = QtWidgets.QDoubleSpinBox(self.widget1)
        self.hipRollRightBox.setDecimals(3)
        self.hipRollRightBox.setObjectName("hipRollRightBox")
        self.verticalLayout_18.addWidget(self.hipRollRightBox)
        self.horizontalLayout.addLayout(self.verticalLayout_18)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(584, 790, 106, 50))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.ankleRollLabelLeft = QtWidgets.QLabel(self.widget2)
        self.ankleRollLabelLeft.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.ankleRollLabelLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.ankleRollLabelLeft.setObjectName("ankleRollLabelLeft")
        self.verticalLayout_11.addWidget(self.ankleRollLabelLeft)
        self.ankleRollLeftBox = QtWidgets.QDoubleSpinBox(self.widget2)
        self.ankleRollLeftBox.setDecimals(3)
        self.ankleRollLeftBox.setObjectName("ankleRollLeftBox")
        self.verticalLayout_11.addWidget(self.ankleRollLeftBox)
        self.widget3 = QtWidgets.QWidget(self.centralwidget)
        self.widget3.setGeometry(QtCore.QRect(710, 790, 106, 50))
        self.widget3.setObjectName("widget3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.anklePitchLabelLeft = QtWidgets.QLabel(self.widget3)
        self.anklePitchLabelLeft.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.anklePitchLabelLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.anklePitchLabelLeft.setObjectName("anklePitchLabelLeft")
        self.verticalLayout_10.addWidget(self.anklePitchLabelLeft)
        self.anklePitchLeftBox = QtWidgets.QDoubleSpinBox(self.widget3)
        self.anklePitchLeftBox.setDecimals(3)
        self.anklePitchLeftBox.setObjectName("anklePitchLeftBox")
        self.verticalLayout_10.addWidget(self.anklePitchLeftBox)
        self.widget4 = QtWidgets.QWidget(self.centralwidget)
        self.widget4.setGeometry(QtCore.QRect(80, 790, 107, 50))
        self.widget4.setObjectName("widget4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget4)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.ankleRollLabelRight = QtWidgets.QLabel(self.widget4)
        self.ankleRollLabelRight.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.ankleRollLabelRight.setAlignment(QtCore.Qt.AlignCenter)
        self.ankleRollLabelRight.setObjectName("ankleRollLabelRight")
        self.verticalLayout_8.addWidget(self.ankleRollLabelRight)
        self.ankleRollRightBox = QtWidgets.QDoubleSpinBox(self.widget4)
        self.ankleRollRightBox.setDecimals(3)
        self.ankleRollRightBox.setObjectName("ankleRollRightBox")
        self.verticalLayout_8.addWidget(self.ankleRollRightBox)
        self.widget5 = QtWidgets.QWidget(self.centralwidget)
        self.widget5.setGeometry(QtCore.QRect(207, 790, 106, 50))
        self.widget5.setObjectName("widget5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget5)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.anklePitchLabelRight = QtWidgets.QLabel(self.widget5)
        self.anklePitchLabelRight.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.anklePitchLabelRight.setAlignment(QtCore.Qt.AlignCenter)
        self.anklePitchLabelRight.setObjectName("anklePitchLabelRight")
        self.verticalLayout_9.addWidget(self.anklePitchLabelRight)
        self.anklePitchRightBox = QtWidgets.QDoubleSpinBox(self.widget5)
        self.anklePitchRightBox.setDecimals(3)
        self.anklePitchRightBox.setObjectName("anklePitchRightBox")
        self.verticalLayout_9.addWidget(self.anklePitchRightBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 953, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Motion Tool"))
        self.headPitchLabel.setText(_translate("MainWindow", "Head pitch"))
        self.kneePitchLabelRight.setText(_translate("MainWindow", "Knee pitch"))
        self.shoulderPitchLabelLeft.setText(_translate("MainWindow", "Shoulder pitch"))
        self.shoulderRollLabelLeft.setText(_translate("MainWindow", "Shoulder roll"))
        self.elbowPitchLabeLeft.setText(_translate("MainWindow", "Elbow pitch"))
        self.kneePitchLabelLeft.setText(_translate("MainWindow", "Knee pitch"))
        self.elbowPitchLabelRight.setText(_translate("MainWindow", "Elbow pitch"))
        self.shoulderRollLabelRight.setText(_translate("MainWindow", "Shoulder roll"))
        self.shoulderPitchLabelRight.setText(_translate("MainWindow", "Shoulder pitch"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.setButton.setText(_translate("MainWindow", "Set"))
        self.pos0Button.setText(_translate("MainWindow", "Pos 0"))
        self.headPitchLabel_2.setText(_translate("MainWindow", "Head yaw"))
        self.hipYawLabelLeft.setText(_translate("MainWindow", "Hip yaw"))
        self.hipRollLabelLeft.setText(_translate("MainWindow", "Hip roll"))
        self.hipPitchLabelLeft.setText(_translate("MainWindow", "Hip pitch"))
        self.hipYawLabelRight.setText(_translate("MainWindow", "Hip yaw"))
        self.hipPitchLabelRight.setText(_translate("MainWindow", "Hip pitch"))
        self.hipRollLabelRight.setText(_translate("MainWindow", "Hip roll"))
        self.ankleRollLabelLeft.setText(_translate("MainWindow", "Ankle roll"))
        self.anklePitchLabelLeft.setText(_translate("MainWindow", "Ankle pitch"))
        self.ankleRollLabelRight.setText(_translate("MainWindow", "Ankle roll"))
        self.anklePitchLabelRight.setText(_translate("MainWindow", "Ankle pitch"))

